### ISSUE TITLE
Why use strong passwords?

### ISSUE THREAD

**Issue by smutt** [icann/resolver-testbed#4]
When setting up debian960-base it is recommended to use a strong password for root.
"Root password: This will be used for all interaction with all VMs, so use a strong one"

Why? We're creating a network that can only be accessed on the host machine. Why not use a simple weak password that can be more easily remembered? I never use strong passwords when setting up VMs because it just makes it more likely I'll forget it.

I'm wondering if you know something I don't.

**Comment by paulehoffman** [comment]
One of the VMs in the network (the gateway VM) has connections to the outside world. That VM is connected to all the others. I do not want to assume that that VM will never allow login from its outside interface, so a strong password is needed.

**Comment by smutt** [comment]
I'm not sure that's a legitimate concer because the gateway-vm is behind NAT, and these VMs aren't running all the time, they're only started as needed. But if this is the concern then why not disable SSHD on the gateway-vm port that faces the NAT? This is port 'gi' in your diagram.

**Comment by paulehoffman** [comment]
The NAT that gateway-vm is behind might have pinholes or other ways of the outside reaching the VMs. It still seems prudent to suggest a strong password.
