### ISSUE TITLE
Paramiko requires 'legacy PEM' RSA private keyfiles

### ISSUE THREAD

**Issue by smutt** [icann/resolver-testbed#6]
fabric for Python 3 depends on paramiko for the actual SSH connections and paramiko is somewhat finicky about RSA private key files. Paramiko wants what the OpenSSH manpage calls 'legacy PEM' formatted RSA private key files. By default ssh-keygen creates RFC4716 formatted keys.

This works:
ssh-keygen -m pem
-----BEGIN RSA PRIVATE KEY-----

This does not work:
ssh-keygen
-----BEGIN OPENSSH PRIVATE KEY-----

There is an argument to be made that OpenSSH is actually at fault here for not following RFC4716 completely. RFC4716 keyfiles should start with:
---- BEGIN SSH2 PUBLIC KEY ----

Found using OpenSSH 7.9p1-1 on Manjaro Linux.

**Comment by paulehoffman** [comment]
Still not sure how to address this in the setup instructions.

**Comment by paulehoffman** [comment]
Apparently fixed by the giant commit
