### ISSUE TITLE
Python required for dnssec-keymgr 

### ISSUE THREAD

**Issue by paulitrix** [icann/resolver-testbed#8]
While running _./rt.py make_resolvers_ I got the following bug:

_Making with './configure --prefix=/root/Target/bind-9.14.0 && make && make install'_

_making failed with 'configure: error: Python required for dnssec-keymgr_

_'. Exiting._

A similar error was reported on the following link: https://gitlab.isc.org/isc-projects/bind9/issues/958 

A quick fix was to install the _ply_ dependency using the command _pip3 install ply_ but was wondering if this is the best approach?

**Comment by paulehoffman** [comment]
Fixed by changing the instructions for building BIND to not require python.
