### ISSUE TITLE
OpenSSL/LibreSSL not found 

### ISSUE THREAD

**Issue by paulitrix** [icann/resolver-testbed#9]
Also while running _./rt.py make_resolvers_ I got the following error despite the fact that OpenSSL was already installed:

_Making with './configure --prefix=/root/Target/bind-9.13.6 && make && make install'
making failed with 'configure: error: in `/root/Source/bind-9.13.6':
configure: error: OpenSSL/LibreSSL not found_

The error log further states:

_making failed with 'configure: error: OpenSSL was not found in any of /usr /usr/local /usr/local/ssl /usr/pkg /usr/sfw; use --with-openssl=/path
If you don't want OpenSSL, use --without-openssl
'. Exiting._

How do you go about fixing this?

**Comment by paulehoffman** [comment]
This was resolved f2f by seeing that the setup instructions were not followed correctly.
